version: "3.7"
services:
  api_service:
    build: ./backend
    restart: always
    ports:
      - 8888:8888
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/chat
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: ddlChallenge
      MYSQL_PASSWORD: ddlChallenge
      MYSQL_ROOT_PASSWORD: ddlChallenge

  webapp:
    build: ./frontend
    restart: always
    ports:
      - 3100:80

networks:
  springapimysql-net:
