spring:
  application:
    name: fe-core-challenge
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: ddlChallenge
    password: ddlChallenge
  sql:
    init:
      mode: always
server:
  port: 8888
