CREATE TABLE IF NOT EXISTS `messages` (
`id` bigint NOT NULL AUTO_INCREMENT,
`body` TEXT DEFAULT NULL,
`sent_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
`sender_username` VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;